# Terminal behavior
enable_audio_bell no
enabled_layouts tall, fat
dynamic_background_opacity yes
allow_remote_control yes
listen_on unix:/tmp/mykitty


# Fonts
font_family      family="JetBrainsMono Nerd Font"
bold_font        auto
italic_font      auto
bold_italic_font auto

# Tabs conf
include tabs.conf

# BEGIN_KITTY_THEME
# Moonfly
include current-theme.conf
# END_KITTY_THEME
