[MainWindow]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\x5\x5\0\0\0\n\0\0\t\xf5\0\0\x5i\0\0\x5\x5\0\0\0\n\0\0\t\xf5\0\0\x5i\0\0\0\0\0\0\0\0\n\0\0\0\x5\x5\0\0\0\n\0\0\t\xf5\0\0\x5i)

[Settings]
checkRcloneBrowserUpdates=true
checkRcloneUpdates=true
darkMode=false
darkModeIni=false
defaultDownloadOptions=
defaultRcloneOptions=--fast-list
defaultUploadOptions=
driveShared=0
http_proxy=
https_proxy=
iconSize=medium
lastRcloneBrowserUpdateCheck=Thu Sep 29 2022
lastRcloneUpdateCheck=Thu Sep 29 2022
lastUsedDestFolder=
lastUsedSourceFolder=
no_proxy=
rclone=/usr/bin/rclone
rcloneVersion=1.57.0
useProxy=false
