[MainWindow]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\0\0\0\0\0\0\0\x5\xad\0\0\x5s\0\0\0\0\0\0\0%\0\0\x5\xad\0\0\x5s\0\0\0\0\0\0\0\0\n\0\0\0\0\0\0\0\0%\0\0\x5\xad\0\0\x5s)

[Settings]
checkRcloneBrowserUpdates=true
checkRcloneUpdates=true
darkMode=false
darkModeIni=false
defaultDownloadOptions=
defaultRcloneOptions=--fast-list
defaultUploadOptions=
driveShared=0
http_proxy=
https_proxy=
iconSize=medium
lastRcloneBrowserUpdateCheck=Sat Aug 13 2022
lastRcloneUpdateCheck=Sat Aug 13 2022
lastUsedDestFolder=
lastUsedSourceFolder=
no_proxy=
rclone=/usr/bin/rclone
rcloneVersion=1.57.0
useProxy=false
