[MainWindow]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\b\0\0\0\b\0\0\x5\xf7\0\0\x3\x34\0\0\0\b\0\0\0\b\0\0\x5\xf7\0\0\x3\x34\0\0\0\0\0\0\0\0\x6\0\0\0\0\b\0\0\0\b\0\0\x5\xf7\0\0\x3\x34)

[Settings]
checkRcloneBrowserUpdates=true
checkRcloneUpdates=true
darkMode=false
darkModeIni=false
defaultDownloadOptions=
defaultRcloneOptions=--fast-list
defaultUploadOptions=
driveShared=0
http_proxy=
https_proxy=
iconSize=medium
lastRcloneBrowserUpdateCheck=Sun Dec 11 2022
lastRcloneUpdateCheck=Sun Dec 11 2022
lastUsedDestFolder=
lastUsedSourceFolder=
no_proxy=
rclone=/usr/bin/rclone
rcloneVersion=1.57.0
useProxy=false
